strictness: veryhigh
doc-warnings: yes
max-line-length: 200

dodgy:
    # looks for 'dodgy' things like passwords or git conflict artifacts
    run: true

mccabe:
    # complexity checking.
    run: true

pep257:
    # docstring checking
    run: true

pep8:
    run: true

pyflakes:
    run: true

pylint:
    run: true
    disable:
        - W0142 # * or ** magic
        - W0141 # filter()

pyroma:
    #check packaging
    run: true

vulture:
    # find unused code
    run: true
